
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Stack;
import javax.swing.JComboBox;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Menasi
 */
public class DataEntry extends javax.swing.JFrame {

    /**
     * Creates new form DataEntry
     */
    public DataEntry() {
        initComponents();
        p_add_verse.setVisible(false);
        p_create_lesson.setVisible(false);
        p_create_module.setVisible(false);
        p_create_question.setVisible(false);
        p_create_faq.setVisible(false);
        p_add_lang.setVisible(false);
       
        
        
    }

    public Font font = new Font("Nyala", 11, 16);
    private static final String MODULE_LIST = "ModuleList.txt";
    private static final String MODULE_JAVA = "codeModule.java";
    private static final String LESSON_LIST = "LessonList.txt";
    private static final String LESSON_CODE = "codeLesson.java";
    private static final String LESSON_TODO = "LessonTODO.txt";
    private static final String QUESTION_LIST = "QuestionList.txt";
    private static final String QUESTION_CODE = "codeQuestion.java";
    private static final String QUESTION_TODO= "QuestionTODO.txt";
    
    private static final String FAQ_CODE = "codeFaq.java";
    private static final String CODE_VERSE = "codeVerse.java";
    private static final String CODE_LANG = "codeLang.java";
    private static final String LANG_DONE = "langDone.txt";
    private static final String LANG_TODO = "langTODO.txt";
    private static final String VERSE_TODO = "verseTODO.txt";
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        p_home_panel = new javax.swing.JPanel();
        b_create_module = new javax.swing.JButton();
        b_create_lesson = new javax.swing.JButton();
        b_create_question = new javax.swing.JButton();
        b_create_faq = new javax.swing.JButton();
        b_add_verse = new javax.swing.JButton();
        b_add_lang = new javax.swing.JButton();
        p_create_module = new javax.swing.JPanel();
        b_module_back = new javax.swing.JButton();
        tf_module_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_module_title = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b_module_created = new javax.swing.JButton();
        tf_module_st_lesson = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p_create_lesson = new javax.swing.JPanel();
        b_lesson_back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_lesson_titile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb_lesson_pr_lesson = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_lesson_mod_id = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tf_lesson_nxt_lesson = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_lesson_st_question = new javax.swing.JTextField();
        b_lesson_created = new javax.swing.JButton();
        cb_lesson_lesson_id = new javax.swing.JComboBox<>();
        p_create_question = new javax.swing.JPanel();
        b_question_back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cb_question_id = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cb_question_prev = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        tf_question_nxt_question = new javax.swing.JTextField();
        b_question_created = new javax.swing.JButton();
        p_create_faq = new javax.swing.JPanel();
        b_faq_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_faq_id = new javax.swing.JTextField();
        b_faq_created = new javax.swing.JButton();
        p_add_verse = new javax.swing.JPanel();
        b_verse_back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        b_verse_created = new javax.swing.JButton();
        cb_verse_id = new javax.swing.JComboBox<>();
        p_add_lang = new javax.swing.JPanel();
        b_lang_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        b_lang_created = new javax.swing.JButton();
        cb_lang_id = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_lang_amahric = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_lang_eng = new javax.swing.JTextArea();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Entery");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        p_home_panel.setBackground(new java.awt.Color(255, 255, 255));

        b_create_module.setText("Create Module");
        b_create_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_create_moduleActionPerformed(evt);
            }
        });

        b_create_lesson.setText("Create Lesson");
        b_create_lesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_create_lessonActionPerformed(evt);
            }
        });

        b_create_question.setText("Create Quession");
        b_create_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_create_questionActionPerformed(evt);
            }
        });

        b_create_faq.setText("Create FAQ");
        b_create_faq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_create_faqActionPerformed(evt);
            }
        });

        b_add_verse.setText("Add Verse");
        b_add_verse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_add_verseActionPerformed(evt);
            }
        });

        b_add_lang.setText("Add Lang");
        b_add_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_add_langActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_home_panelLayout = new javax.swing.GroupLayout(p_home_panel);
        p_home_panel.setLayout(p_home_panelLayout);
        p_home_panelLayout.setHorizontalGroup(
            p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_home_panelLayout.createSequentialGroup()
                .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_home_panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_create_module)
                            .addComponent(b_create_question))
                        .addGap(112, 112, 112)
                        .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_create_faq)
                            .addComponent(b_create_lesson)))
                    .addGroup(p_home_panelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(b_add_verse)
                        .addGap(43, 43, 43)
                        .addComponent(b_add_lang)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        p_home_panelLayout.setVerticalGroup(
            p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_home_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_create_module)
                    .addComponent(b_create_lesson))
                .addGap(40, 40, 40)
                .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_create_question)
                    .addComponent(b_create_faq))
                .addGap(27, 27, 27)
                .addGroup(p_home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add_verse)
                    .addComponent(b_add_lang))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        p_create_module.setBackground(new java.awt.Color(255, 255, 255));

        b_module_back.setText("Back");
        b_module_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_module_backActionPerformed(evt);
            }
        });

        tf_module_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_module_idActionPerformed(evt);
            }
        });

        jLabel1.setText("Moudle ID");

        tf_module_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_module_titleActionPerformed(evt);
            }
        });

        jLabel6.setText("Moudle Title");

        b_module_created.setText("Create");
        b_module_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_module_createdActionPerformed(evt);
            }
        });

        tf_module_st_lesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_module_st_lessonActionPerformed(evt);
            }
        });

        jLabel8.setText("St. Lesson");

        javax.swing.GroupLayout p_create_moduleLayout = new javax.swing.GroupLayout(p_create_module);
        p_create_module.setLayout(p_create_moduleLayout);
        p_create_moduleLayout.setHorizontalGroup(
            p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_create_moduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_module_back)
                .addGap(30, 30, 30)
                .addComponent(b_module_created)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_create_moduleLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_create_moduleLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(tf_module_st_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_create_moduleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_module_id, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_module_title, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        p_create_moduleLayout.setVerticalGroup(
            p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_moduleLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_module_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_module_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_module_st_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(p_create_moduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_module_back)
                    .addComponent(b_module_created))
                .addContainerGap())
        );

        p_create_lesson.setBackground(new java.awt.Color(255, 255, 255));

        b_lesson_back.setText("Back");
        b_lesson_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lesson_backActionPerformed(evt);
            }
        });

        jLabel11.setText("Lesson ID");

        jLabel13.setText("Lesson Title");

        tf_lesson_titile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lesson_titileActionPerformed(evt);
            }
        });

        jLabel2.setText("Pr. Lesson");

        cb_lesson_pr_lesson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Lesson Module");

        cb_lesson_mod_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Next Lesson");

        tf_lesson_nxt_lesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lesson_nxt_lessonActionPerformed(evt);
            }
        });

        jLabel15.setText("St. Question");

        tf_lesson_st_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lesson_st_questionActionPerformed(evt);
            }
        });

        b_lesson_created.setText("Create");
        b_lesson_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lesson_createdActionPerformed(evt);
            }
        });

        cb_lesson_lesson_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p_create_lessonLayout = new javax.swing.GroupLayout(p_create_lesson);
        p_create_lesson.setLayout(p_create_lessonLayout);
        p_create_lessonLayout.setHorizontalGroup(
            p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_create_lessonLayout.createSequentialGroup()
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_create_lessonLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cb_lesson_mod_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_create_lessonLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_lesson_lesson_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_lesson_nxt_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_create_lessonLayout.createSequentialGroup()
                                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_lesson_pr_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_lesson_titile, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_create_lessonLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tf_lesson_st_question, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_lessonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_lesson_back)
                .addGap(18, 18, 18)
                .addComponent(b_lesson_created)
                .addGap(46, 46, 46))
        );
        p_create_lessonLayout.setVerticalGroup(
            p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_lessonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_lesson_mod_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_lesson_lesson_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_lesson_titile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_lesson_pr_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf_lesson_nxt_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_lesson_st_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(p_create_lessonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_lesson_back)
                    .addComponent(b_lesson_created))
                .addContainerGap())
        );

        p_create_question.setBackground(new java.awt.Color(255, 255, 255));

        b_question_back.setText("Back");
        b_question_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_question_backActionPerformed(evt);
            }
        });

        jLabel9.setText("Question ID");

        cb_question_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("Pr. Que");

        cb_question_prev.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel24.setText("Next Que");

        b_question_created.setText("Create");
        b_question_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_question_createdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_create_questionLayout = new javax.swing.GroupLayout(p_create_question);
        p_create_question.setLayout(p_create_questionLayout);
        p_create_questionLayout.setHorizontalGroup(
            p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_questionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_question_back)
                .addGap(18, 18, 18)
                .addComponent(b_question_created)
                .addGap(19, 19, 19))
            .addGroup(p_create_questionLayout.createSequentialGroup()
                .addGroup(p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_create_questionLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cb_question_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(cb_question_prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_create_questionLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27)
                        .addComponent(tf_question_nxt_question, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        p_create_questionLayout.setVerticalGroup(
            p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_questionLayout.createSequentialGroup()
                .addGroup(p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_create_questionLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cb_question_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(cb_question_prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_questionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(tf_question_nxt_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(p_create_questionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_question_back)
                    .addComponent(b_question_created))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_create_faq.setBackground(new java.awt.Color(255, 255, 255));

        b_faq_back.setText("Back");
        b_faq_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_faq_backActionPerformed(evt);
            }
        });

        jLabel3.setText("Faq_id");

        tf_faq_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_faq_idActionPerformed(evt);
            }
        });

        b_faq_created.setText("Create");
        b_faq_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_faq_createdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_create_faqLayout = new javax.swing.GroupLayout(p_create_faq);
        p_create_faq.setLayout(p_create_faqLayout);
        p_create_faqLayout.setHorizontalGroup(
            p_create_faqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_faqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_faq_back)
                .addGap(18, 18, 18)
                .addComponent(b_faq_created)
                .addGap(41, 41, 41))
            .addGroup(p_create_faqLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(tf_faq_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        p_create_faqLayout.setVerticalGroup(
            p_create_faqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_create_faqLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(p_create_faqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_faq_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addGroup(p_create_faqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_faq_back)
                    .addComponent(b_faq_created))
                .addContainerGap())
        );

        p_add_verse.setBackground(new java.awt.Color(255, 255, 255));

        b_verse_back.setText("Back");
        b_verse_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_verse_backActionPerformed(evt);
            }
        });

        jLabel4.setText("Verse_id");

        b_verse_created.setText("Create");
        b_verse_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_verse_createdActionPerformed(evt);
            }
        });

        cb_verse_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p_add_verseLayout = new javax.swing.GroupLayout(p_add_verse);
        p_add_verse.setLayout(p_add_verseLayout);
        p_add_verseLayout.setHorizontalGroup(
            p_add_verseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_verseLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(b_verse_back)
                .addGap(18, 18, 18)
                .addComponent(b_verse_created)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_verseLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cb_verse_id, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_add_verseLayout.setVerticalGroup(
            p_add_verseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_verseLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(p_add_verseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_verse_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(p_add_verseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_verse_back)
                    .addComponent(b_verse_created))
                .addContainerGap())
        );

        p_add_lang.setBackground(new java.awt.Color(255, 255, 255));

        b_lang_back.setText("Back");
        b_lang_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lang_backActionPerformed(evt);
            }
        });

        jLabel5.setText("Lang Id");

        jLabel29.setText("Lang Ahmaric");

        jLabel30.setText("Lang Eng");

        b_lang_created.setText("Create");
        b_lang_created.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lang_createdActionPerformed(evt);
            }
        });

        cb_lang_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ta_lang_amahric.setColumns(20);
        ta_lang_amahric.setRows(5);
        jScrollPane1.setViewportView(ta_lang_amahric);

        ta_lang_eng.setColumns(20);
        ta_lang_eng.setRows(5);
        jScrollPane2.setViewportView(ta_lang_eng);

        javax.swing.GroupLayout p_add_langLayout = new javax.swing.GroupLayout(p_add_lang);
        p_add_lang.setLayout(p_add_langLayout);
        p_add_langLayout.setHorizontalGroup(
            p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_langLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_lang_back)
                .addGap(18, 18, 18)
                .addComponent(b_lang_created)
                .addGap(44, 44, 44))
            .addGroup(p_add_langLayout.createSequentialGroup()
                .addGroup(p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_add_langLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cb_lang_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p_add_langLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(p_add_langLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(132, 132, 132))
        );
        p_add_langLayout.setVerticalGroup(
            p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_add_langLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_lang_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(p_add_langLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_lang_back)
                    .addComponent(b_lang_created))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(p_create_module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 145, Short.MAX_VALUE)
                    .addComponent(p_create_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 141, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 181, Short.MAX_VALUE)
                    .addComponent(p_create_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 176, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 181, Short.MAX_VALUE)
                    .addComponent(p_create_faq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 176, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 181, Short.MAX_VALUE)
                    .addComponent(p_add_verse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 176, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(p_home_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(p_add_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(p_create_module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 66, Short.MAX_VALUE)
                    .addComponent(p_create_lesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 66, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(p_create_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 79, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(p_create_faq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 79, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(p_add_verse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 79, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(p_home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(66, 66, 66)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(p_add_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_module_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_module_backActionPerformed
      
        p_create_module.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_module_backActionPerformed

    private void b_lesson_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lesson_backActionPerformed
       p_create_lesson.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_lesson_backActionPerformed

    private void b_faq_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_faq_backActionPerformed
        p_create_faq.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_faq_backActionPerformed

    private void b_verse_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_verse_backActionPerformed
        p_add_verse.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_verse_backActionPerformed

    private void b_add_verseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_add_verseActionPerformed
        p_home_panel.setVisible(false);
        ReadFromFile(VERSE_TODO, cb_verse_id);
        p_add_verse.setVisible(true);
    }//GEN-LAST:event_b_add_verseActionPerformed

    private void b_create_faqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_create_faqActionPerformed
        p_home_panel.setVisible(false);
        p_create_faq.setVisible(true);
    }//GEN-LAST:event_b_create_faqActionPerformed

    private void b_create_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_create_questionActionPerformed
        p_home_panel.setVisible(false);
        updateQuestionComboBox();
        p_create_question.setVisible(true);
    }//GEN-LAST:event_b_create_questionActionPerformed

    private void b_create_lessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_create_lessonActionPerformed
   
        p_home_panel.setVisible(false);
        updateLessonComboBox();
        p_create_lesson.setVisible(true);
    }//GEN-LAST:event_b_create_lessonActionPerformed

    private void b_create_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_create_moduleActionPerformed

        p_home_panel.setVisible(false);
        p_create_module.setVisible(true);
    }//GEN-LAST:event_b_create_moduleActionPerformed

    private void tf_module_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_module_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_module_idActionPerformed

    private void tf_module_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_module_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_module_titleActionPerformed

    private void b_module_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_module_createdActionPerformed
        
        String code;
        String modeId = tf_module_id.getText();
        String modeTitle = modeId+"Title"+tf_module_title.getText();
        String modeStLesson = modeId+tf_module_st_lesson.getText();
        
        code = "new Module(\""+modeId+"\", \""+modeTitle
                +"\", \"" +modeStLesson+"\" , \"0\"),";
        
        WriteOnFIle(code, MODULE_JAVA);
        WriteOnFIle(modeId,MODULE_LIST);
        WriteOnFIle(modeStLesson,LESSON_TODO);
        WriteOnFIle(modeTitle,LANG_TODO);
        tf_module_id.setText("");
        tf_module_title.setText("");
        tf_module_st_lesson.setText("");
        
        
    }//GEN-LAST:event_b_module_createdActionPerformed

    private void tf_lesson_titileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lesson_titileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lesson_titileActionPerformed

    private void tf_lesson_nxt_lessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lesson_nxt_lessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lesson_nxt_lessonActionPerformed

    private void tf_lesson_st_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lesson_st_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lesson_st_questionActionPerformed

    private void tf_module_st_lessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_module_st_lessonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_module_st_lessonActionPerformed

    private void tf_faq_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_faq_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_faq_idActionPerformed

    private void b_lang_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lang_backActionPerformed
        p_add_lang.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_lang_backActionPerformed

    private void b_add_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_add_langActionPerformed
        p_add_lang.setVisible(true);
        ta_lang_amahric.setFont(font);
        ReadFromFile(LANG_TODO, cb_lang_id);
        p_home_panel.setVisible(false);
    }//GEN-LAST:event_b_add_langActionPerformed

    private void b_lesson_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lesson_createdActionPerformed
        
        String code;
        String LessonPrLesson="null";
        String LessonID = cb_lesson_lesson_id.getSelectedItem().toString();
        String LessonMod = cb_lesson_mod_id.getSelectedItem().toString();
        String LessonTitle = LessonID+"Title"+tf_lesson_titile.getText();
        String LessonString = LessonID+"String";
        
        String LessonNxtLesson = LessonMod+tf_lesson_nxt_lesson.getText();
        String LessonStQuestion = LessonID+tf_lesson_st_question.getText();
        
        try {
          
        LessonPrLesson =cb_lesson_pr_lesson.getSelectedItem().toString();
        } catch (Exception e) {
        }
        
        if(LessonNxtLesson.equalsIgnoreCase(LessonMod))
            LessonNxtLesson = "null";
        if(LessonStQuestion.equalsIgnoreCase(LessonID))
            LessonStQuestion = "null";
        
        code = "new Lesson(\""+LessonID+"\", \""+LessonMod
                +"\", \"" +LessonTitle+"\" , \"" +LessonString+"\" ,"
                + " \"" +LessonPrLesson+"\" , \"" +LessonNxtLesson+"\" , "
                + "\"" +LessonStQuestion+"\"),";
        
        WriteOnFIle(code, LESSON_CODE);
        WriteOnFIle(LessonID,LESSON_LIST);
        WriteOnFIle(LessonTitle,LANG_TODO);
        WriteOnFIle(LessonString,LANG_TODO);
        RemoveFromFIle(LessonID, LESSON_TODO);
        WriteOnFIle(LessonNxtLesson,LESSON_TODO);
        WriteOnFIle(LessonStQuestion,QUESTION_TODO);
        
        tf_lesson_nxt_lesson.setText("");
        tf_lesson_st_question.setText("");
        tf_lesson_titile.setText("");
        updateLessonComboBox();
        
        
        
        
        
        
    }//GEN-LAST:event_b_lesson_createdActionPerformed

    private void b_question_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_question_createdActionPerformed

        String code;

        String QUESTION_ID = cb_question_id.getSelectedItem().toString();
        String QUESTION  = QUESTION_ID+"Question";
        String CHOICE_A  = QUESTION_ID+"ChA";
        String CHOICE_B  = QUESTION_ID+"ChB";
        String CHOICE_C  = QUESTION_ID+"ChC";
        String CHOICE_D  = QUESTION_ID+"ChD";
        String QUESTION_ANS  = QUESTION_ID+"Ans";
        String QUESTION_HINT   = QUESTION_ID+"Hint";
        String _PR_QUESTION  = "null";
        String _NXT_QUESTION  = "null";
        String QuestionPreFix = QUESTION_ID.substring(0, 9);
        
        try {
            _PR_QUESTION = cb_question_prev.getSelectedItem().toString();
        } catch (Exception e) {
        }
        
        if(!tf_question_nxt_question.getText().equalsIgnoreCase(""))
            _NXT_QUESTION = QuestionPreFix+tf_question_nxt_question.getText();
        
         code = "new Question(\""+QUESTION_ID+"\", \""+QUESTION
                +"\", \"" +CHOICE_A+"\" , \"" +CHOICE_B+"\" ,"
                + " \"" +CHOICE_C+"\" , \"" +CHOICE_D+"\" , "
                + "\"" +QUESTION_ANS+"\",\" "+QUESTION_HINT+"\",\""+_PR_QUESTION
                 +"\",\""+_NXT_QUESTION+"\"),";
       
        WriteOnFIle(code, QUESTION_CODE);
        WriteOnFIle(QUESTION_ID, QUESTION_LIST);
        WriteOnFIle(QUESTION+"\n"+
                    CHOICE_A+"\n"+
                    CHOICE_B+"\n"+
                    CHOICE_C+"\n"+
                    CHOICE_D+"\n"+
                    QUESTION_ANS+"\n"+
                    QUESTION_HINT, LANG_TODO);
        if(!_NXT_QUESTION.equalsIgnoreCase("null"))
            WriteOnFIle(_NXT_QUESTION,QUESTION_TODO);
        RemoveFromFIle(QUESTION_ID, QUESTION_TODO);
        updateQuestionComboBox();
        tf_question_nxt_question.setText("");
        
    }//GEN-LAST:event_b_question_createdActionPerformed

    private void b_question_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_question_backActionPerformed
        p_create_question.setVisible(false);
        p_home_panel.setVisible(true);
    }//GEN-LAST:event_b_question_backActionPerformed

    private void b_faq_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_faq_createdActionPerformed

        String code;
        String FAQ_Id = "FAQ"+tf_faq_id.getText();
        FAQ_Id = FAQ_Id.replace(' ', '_');
        String FAQ_Question = FAQ_Id+"Question";
        String FAQ_Ans= FAQ_Id+"Ans";
        
        
        
        code = "new FAQ(\""+FAQ_Id+"\", \""+FAQ_Question
                +"\", \"" +FAQ_Ans+"\"),";
        WriteOnFIle(code,FAQ_CODE);
        WriteOnFIle(FAQ_Question+"\n"+FAQ_Ans, LANG_TODO);
        tf_faq_id.setText("");

       
    }//GEN-LAST:event_b_faq_createdActionPerformed

    private void b_verse_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_verse_createdActionPerformed
      String code;
        String Vers_Id = cb_verse_id.getSelectedItem().toString();
        Vers_Id = Vers_Id.replace(' ', '_');
        String Vers_Display = Vers_Id+"Display";
        String Verse_Str= Vers_Id+"String";
        
        
        
        code = "new Verse(\""+Vers_Id+"\", \""+Vers_Display
                +"\", \"" +Verse_Str+"\"),";
        WriteOnFIle(code,CODE_VERSE);
        WriteOnFIle(Vers_Display+"\n"+Verse_Str, LANG_TODO);
        RemoveFromFIle(Vers_Id, VERSE_TODO);
        ReadFromFile(VERSE_TODO, cb_verse_id);
    }//GEN-LAST:event_b_verse_createdActionPerformed

    private void b_lang_createdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lang_createdActionPerformed
        String code;
        String Lang_Id = cb_lang_id.getSelectedItem().toString();
        String Lang_Amh =ta_lang_amahric.getText();
        String Lang_Eng = ta_lang_eng.getText();
        
        extactVerse(Lang_Amh,VERSE_TODO);
        extactVerse(Lang_Eng,VERSE_TODO);
        
        code = "new Lang(\""+Lang_Id+"\", \""+Lang_Amh
                +"\", \"" +Lang_Eng+"\"),";
        WriteOnFIle(code, CODE_LANG);
        WriteOnFIle(Lang_Id, LANG_DONE);
        RemoveFromFIle(Lang_Id, LANG_TODO);
        ta_lang_amahric.setText(""); 
        ta_lang_eng.setText("");
        
        
        
        ReadFromFile(LANG_TODO, cb_lang_id);
        
        
        
        
        
    }//GEN-LAST:event_b_lang_createdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntry().setVisible(true);
            }
        });
    }
    
    
    private void WriteOnFIle(String code, String fileName) {
   Path path;
   
       path= Paths.get(fileName);
   
        Charset caset = Charset.forName("UTF-8");
        ArrayList<String> lines = new ArrayList<>();
        try(BufferedReader reader = Files.newBufferedReader(path, caset) ) {
            String line = null;
            while((line= reader.readLine())!= null)
            {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }

        try(BufferedWriter writer = Files.newBufferedWriter(path, caset)) {
            
          
            Iterator<String> iter = lines.iterator();
            while(iter.hasNext())
            {
                String s = iter.next();
                writer.append(s,0,s.length());
               writer.newLine();
            }
            writer.append(code, 0, code.length());
            writer.newLine();
            //writer.newLine();
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }
    
    private void ReadFromFile(String fileName , JComboBox<String> CB)
    {
        Path path;
   
       path= Paths.get(fileName);
   
        Charset caset = Charset.forName("UTF-8");
        ArrayList<String> lines = new ArrayList<>();
        try(BufferedReader reader = Files.newBufferedReader(path, caset) ) {
            String line = null;
            while((line= reader.readLine())!= null)
            {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
        
        CB.removeAllItems();
        lines.stream().forEach((str) -> {
            CB.addItem(str);
        });
    }
    
    private void RemoveFromFIle(String str, String fileName) {
   Path path;
   
       path= Paths.get(fileName);
   
        Charset caset = Charset.forName("UTF-8");
        ArrayList<String> lines = new ArrayList<>();
        try(BufferedReader reader = Files.newBufferedReader(path, caset) ) {
            String line = null;
            while((line= reader.readLine())!= null)
            {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }

        try(BufferedWriter writer = Files.newBufferedWriter(path, caset)) {
            
          
            Iterator<String> iter = lines.iterator();
            while(iter.hasNext())
            {
                String s = iter.next();
                if(!s.equalsIgnoreCase(str)){
                writer.append(s,0,s.length());
                writer.newLine();
                }
            }
            
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }
    
    private void updateLessonComboBox()
    {
        ReadFromFile(MODULE_LIST,cb_lesson_mod_id);
        ReadFromFile(LESSON_TODO,cb_lesson_lesson_id);
        ReadFromFile(LESSON_LIST,cb_lesson_pr_lesson);
    }
    
    private void updateQuestionComboBox()
    {
        ReadFromFile(QUESTION_LIST,cb_question_prev);
        ReadFromFile(QUESTION_TODO,cb_question_id);
       
    }
    
    private void extactVerse(String str, String fileName)
    {
         ArrayList<String> verse = new ArrayList();
        
        Stack<Integer> ChVers = new Stack<>();
        
        for(int i=0; i<str.length(); i++){
            
            if(str.charAt(i)=='$')
                ChVers.push(i);
        }
        while (!ChVers.isEmpty()) {
            int a =ChVers.pop();
            int b =ChVers.pop();
           verse.add(str.substring(b+1, a));
        }
        for (int i = 0; i < verse.size(); i++) {
            WriteOnFIle(verse.get(i),fileName);
        }
    }
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add_lang;
    private javax.swing.JButton b_add_verse;
    private javax.swing.JButton b_create_faq;
    private javax.swing.JButton b_create_lesson;
    private javax.swing.JButton b_create_module;
    private javax.swing.JButton b_create_question;
    private javax.swing.JButton b_faq_back;
    private javax.swing.JButton b_faq_created;
    private javax.swing.JButton b_lang_back;
    private javax.swing.JButton b_lang_created;
    private javax.swing.JButton b_lesson_back;
    private javax.swing.JButton b_lesson_created;
    private javax.swing.JButton b_module_back;
    private javax.swing.JButton b_module_created;
    private javax.swing.JButton b_question_back;
    private javax.swing.JButton b_question_created;
    private javax.swing.JButton b_verse_back;
    private javax.swing.JButton b_verse_created;
    private javax.swing.JComboBox<String> cb_lang_id;
    private javax.swing.JComboBox<String> cb_lesson_lesson_id;
    private javax.swing.JComboBox<String> cb_lesson_mod_id;
    private javax.swing.JComboBox<String> cb_lesson_pr_lesson;
    private javax.swing.JComboBox<String> cb_question_id;
    private javax.swing.JComboBox<String> cb_question_prev;
    private javax.swing.JComboBox<String> cb_verse_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_add_lang;
    private javax.swing.JPanel p_add_verse;
    private javax.swing.JPanel p_create_faq;
    private javax.swing.JPanel p_create_lesson;
    private javax.swing.JPanel p_create_module;
    private javax.swing.JPanel p_create_question;
    private javax.swing.JPanel p_home_panel;
    private javax.swing.JTextArea ta_lang_amahric;
    private javax.swing.JTextArea ta_lang_eng;
    private javax.swing.JTextField tf_faq_id;
    private javax.swing.JTextField tf_lesson_nxt_lesson;
    private javax.swing.JTextField tf_lesson_st_question;
    private javax.swing.JTextField tf_lesson_titile;
    private javax.swing.JTextField tf_module_id;
    private javax.swing.JTextField tf_module_st_lesson;
    private javax.swing.JTextField tf_module_title;
    private javax.swing.JTextField tf_question_nxt_question;
    // End of variables declaration//GEN-END:variables
}
