/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Scanner;

/**
 *
 * @author Menasi
 */
public class DataEntery extends javax.swing.JFrame {

   public static  Scanner sc = new Scanner(System.in);
    
    public Font font = new Font("Nyala", 11, 16);
    public Album [] albumArry = Album.insertAlbum;
    public Song [] songArry = Song.InsertQuery;
    boolean ISHebretSelcted= false;
    boolean AmlkoMode=false;
    String AlbumName="";
    String AlbumId="";
    int CurrLyricID;
   
    /**
     * Creates new form DataEntery
     */
    public DataEntery() {
        initComponents();
        SubmitArea.setFont(font);
       
        AddAlbums(ISHebretSelcted);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SubmitArea = new javax.swing.JTextPane();
        SubmitButton = new javax.swing.JButton();
        CancleButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AlbumCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SongList = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Scale = new javax.swing.JComboBox<>();
        Style = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        AmlkoModeChe = new javax.swing.JCheckBox();
        Marfiya = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Jtemop = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LoadButon = new javax.swing.JButton();
        Albumid = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        prv = new javax.swing.JButton();
        nxt = new javax.swing.JButton();
        ThatDone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(SubmitArea);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        CancleButton.setText("New");
        CancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        AlbumCombo.setFont(new java.awt.Font("Nyala", 0, 11)); // NOI18N
        AlbumCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbumComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Albums");

        jLabel4.setText("Songs");

        SongList.setFont(new java.awt.Font("Nyala", 0, 11)); // NOI18N
        SongList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SongListActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 204)));

        jLabel1.setText("Scale");

        Scale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "minor", "major", "bati" }));
        Scale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScaleActionPerformed(evt);
            }
        });

        Style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chikchica", "Wollo", "Regge", "Disko", "Walth", "6-8", "5-8", "Ballade" }));

        jLabel2.setText("Style");

        AmlkoModeChe.setText("AmlkoMode");
        AmlkoModeChe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmlkoModeCheActionPerformed(evt);
            }
        });

        Marfiya.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "5th", "6th" }));

        jLabel5.setText("mar");

        jLabel6.setText("Tempo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Marfiya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jtemop, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AmlkoModeChe)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AmlkoModeChe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Scale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtemop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marfiya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setText("Single");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AlbumCombo, 0, 139, Short.MAX_VALUE)
                            .addComponent(SongList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1)))
                .addGap(0, 291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AlbumCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(SongList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LoadButon.setText("Load >>");
        LoadButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButonActionPerformed(evt);
            }
        });

        Albumid.setText(" ");

        Title.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        Title.setText(" ");

        prv.setText("<<");
        prv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvActionPerformed(evt);
            }
        });

        nxt.setText(">>");
        nxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtActionPerformed(evt);
            }
        });

        ThatDone.setFont(new java.awt.Font("Nyala", 0, 11)); // NOI18N
        ThatDone.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(prv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(nxt)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(SubmitButton)
                        .addGap(45, 45, 45)
                        .addComponent(CancleButton)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(LoadButon)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(ThatDone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Albumid)
                .addGap(95, 95, 95)
                .addComponent(Title)
                .addGap(143, 143, 143))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nxt)
                    .addComponent(prv))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(LoadButon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Albumid)
                        .addComponent(ThatDone))
                    .addComponent(Title))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(CancleButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SongListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SongListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SongListActionPerformed

    private void AlbumComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbumComboActionPerformed
        // TODO add your handling code here:
        SelectSongs();
        
    }//GEN-LAST:event_AlbumComboActionPerformed

    private void CancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleButtonActionPerformed
        // TODO add your handling code here:

        SubmitArea.setText("");
    }//GEN-LAST:event_CancleButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        String code;
        int mode;
        if (AmlkoMode) {
               code = "new Song(\""+Title.getText()+"\", \""+Albumid.getText()+
                       "\", \""
                +Lyric()+"\",\""+Scale.getSelectedItem().toString().concat("_")
                        .concat(Style.getSelectedItem().toString()).concat("_")
                        .concat(Jtemop.getValue().toString())+"\""
                       + ",\""+Marfiya.getSelectedItem().toString()+"\"),";
               mode =1;// amlko mode 
               
        }
     else
        {code = "new Song(\""+Title.getText()+"\", \""+Albumid.getText()+"\", \""
                +Lyric()+"\"),";
        mode=0;//not amlko mode
        }
        WriteOnFIle(code,mode);
        ThatDone.setText(Title.getText()+"is Done");

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           if(!ISHebretSelcted){
           jButton1.setText("Hebert");
           ISHebretSelcted=true;
       }
       else{
          jButton1.setText("Singls");
           ISHebretSelcted=false;
       }
           AddAlbums(ISHebretSelcted);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LoadButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButonActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < songArry.length; i++) {
            if (songArry[i].get_title().matches(SongList.getSelectedItem().toString())) {
               SubmitArea.setText(songArry[i].get_actualLyric());
               Title.setText(songArry[i].get_title());
                Albumid.setText(songArry[i].get_albumId());
                CurrLyricID= i;
                continue;
            }
        }
    }//GEN-LAST:event_LoadButonActionPerformed

    private void AmlkoModeCheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmlkoModeCheActionPerformed
        // TODO add your handling code here:
     AmlkoMode = !AmlkoMode;
    }//GEN-LAST:event_AmlkoModeCheActionPerformed

    private void prvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvActionPerformed
        // TODO add your handling code here:
         try {
             --CurrLyricID;
         SubmitArea.setText(songArry[CurrLyricID].get_actualLyric());
             Title.setText(songArry[CurrLyricID].get_title());
                Albumid.setText(songArry[CurrLyricID].get_albumId());
        } catch (Exception e) {
            SubmitArea.setText("ሌላ መዝሙር የለም");
            CurrLyricID=-1;
            
        }

                
    }//GEN-LAST:event_prvActionPerformed

    private void nxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtActionPerformed
        // TODO add your handling code here:
           try {
             ++CurrLyricID;
         SubmitArea.setText(songArry[CurrLyricID].get_actualLyric());
                Title.setText(songArry[CurrLyricID].get_title());
                Albumid.setText(songArry[CurrLyricID].get_albumId());
        } catch (Exception e) {
            SubmitArea.setText("ሌላ መዝሙር የለም");
            CurrLyricID= songArry.length+1;
        }
    }//GEN-LAST:event_nxtActionPerformed


    private String Lyric() {
        String text;
        text = SubmitArea.getText();
        boolean one = false;
        String newS = "";
        try {

            for (int i = 0; i < text.length(); i++) {
                char x = text.charAt(i);
                if (Character.getType(x) == 15 && !one) {

                    one = true;
                    newS += "\\n";
                } else if (Character.getType(x) == 15 && one) {

                    one = false;
                } else {

                    newS += "" + x;
                }
            }

        } catch (Exception e) {
            System.err.println("erro");
        }
        return newS;
    }   
    
    private void AddAlbums(boolean ISHebrt){
        AlbumCombo.removeAllItems();
        for (int i = 0; i < albumArry.length; i++) {
            if(ISHebrt)
            {
                if(albumArry[i].get_isSolo()==0)
                {
                    AlbumCombo.addItem(albumArry[i].getAlbum_Title());
                }
            }
            else
            {
                 if(albumArry[i].get_isSolo()==1)
                {
                    AlbumCombo.addItem(albumArry[i].getAlbum_Title());
                } 
            }
        }
    }
   
    private void SelectSongs(){   
          SongList.removeAllItems();
         
        try {
        AlbumName = AlbumCombo.getSelectedItem().toString();   
        } catch (Exception e) {  
        }
        for (int i = 0; i < albumArry.length; i++) {
            if (albumArry[i].getAlbum_Title().matches(AlbumName)) {
                AlbumId=albumArry[i].getAlbum_id();
                continue;
            }
        }
         for (int i = 0; i < songArry.length; i++) {
            if (songArry[i].get_albumId().matches(AlbumId)) {
                SongList.addItem(songArry[i].get_title());
                
            }
        }
       
    }

    private void WriteOnFIle(String code, int mode) {
   Path path;
   if(mode==1)
       path= Paths.get("amlkoMode.java");
   else
       path= Paths.get("NoneAmlkoMode.java");
   
        Charset caset = Charset.forName("UTF-8");
        ArrayList<String> lines = new ArrayList<>();
        try(BufferedReader reader = Files.newBufferedReader(path, caset) ) {
            String line = null;
            while((line= reader.readLine())!= null)
            {
                lines.add(line);
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }

        try(BufferedWriter writer = Files.newBufferedWriter(path, caset)) {
            
          
            Iterator<String> iter = lines.iterator();
            while(iter.hasNext())
            {
                String s = iter.next();
                writer.append(s,0,s.length());
               writer.newLine();
            }
            writer.append(code, 0, code.length());
            writer.newLine();
            writer.newLine();
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataEntery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataEntery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataEntery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataEntery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlbumCombo;
    private javax.swing.JLabel Albumid;
    private javax.swing.JCheckBox AmlkoModeChe;
    private javax.swing.JButton CancleButton;
    private javax.swing.JSpinner Jtemop;
    private javax.swing.JButton LoadButon;
    private javax.swing.JComboBox<String> Marfiya;
    private javax.swing.JComboBox<String> Scale;
    private javax.swing.JComboBox<String> SongList;
    private javax.swing.JComboBox<String> Style;
    private javax.swing.JTextPane SubmitArea;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel ThatDone;
    private javax.swing.JLabel Title;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nxt;
    private javax.swing.JButton prv;
    // End of variables declaration//GEN-END:variables
}
